print('Hello World!')
print('Whats your first name?')
myName = input()
print('Its good to meet you ' + myName)
print('length of your name is:')
print(len(myName))
print('Whats your age?')
myAge = input()
print('you will be ' + str(int(myAge)+1) + ' in a year.')
